sonar.projectKey=devops-demo

# IMPORTANT
sonar.sources=app
sonar.tests=tests

# FORCE Python detection
sonar.language=py
sonar.inclusions=app/**/*.py

# Coverage
sonar.python.coverage.reportPaths=coverage.xml

# Encoding
sonar.sourceEncoding=UTF-8